version: "3.8"
services:
  kcal-app:
    image: kcal-app-image:1.0
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/postgres

  postgres-db:
    image: kcal-postgres:1.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: